server:
  port: 8088

app:
  api-prefix: /ride-hub/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
          # Path cua gateway
            - Path=${app.api-prefix}/auth/**
          filters:
          # Handle
            - StripPrefix=2

# Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# Swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: ${app.api-prefix}/swagger-ui.html
    urls:
      - name: gateway-docs
        url: ${app.api-prefix}/swagger/docs

open:
  api:
    title: Spring-RideHub
    version: v1.0.0
    description: API Gateway cho Spring-RideHub
    serverUrl: http://${SERVER_IP:localhost}:${server.port}
    serverName: server dev
    api-docs: api-gateway


services:
  auth:
    url: http://localhost:8081
