server:
  port: 8088

app:
  api-prefix: /ride-hub/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
          # Path cua gateway
            - Path=${app.api-prefix}/auth/**
          filters:
          # Handle
            - StripPrefix=2

        - id: notification-service
          uri: lb://notification-service
          predicates:
            # Path cua gateway
            - Path=${app.api-prefix}/notifications/**
          filters:
            # Handle
            - StripPrefix=2

        - id: profile-service
          uri: lb://profile-service
          predicates:
            # Path cua gateway
            - Path=${app.api-prefix}/profiles/**
          filters:
            # Handle
            - StripPrefix=2

        - id: file-service
          uri: lb://file-service
          predicates:
            # Path cua gateway
            - Path=${app.api-prefix}/files/**
          filters:
            # Handle
            - StripPrefix=2

# Eureka-Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# Swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: ${app.api-prefix}/swagger-ui.html
    urls:
      - name: gateway-docs
        url: ${app.api-prefix}/swagger/docs

open:
  api:
    title: Spring-RideHub
    version: v1.0.0
    description: API Gateway cho Spring-RideHub
    serverUrl: http://${SWAGGER_HOST:localhost}:${server.port}
    serverName: api-gateway server


gateway:
  url: ${GATEWAY_URL:http://localhost:8088}
  jwt:
    secret: ${GATEWAY_JWT_SECRET}
    expiry-in-minutes: ${GATEWAY_JWT_EXPIRY_MINUTES:15}
