server:
  port: 8083

spring:
  application:
    name: profile-service

  # Database - Postgresql
  datasource:
    url: ${DB_PROFILE_URL:jdbc:postgresql://localhost:5432/ridehub_profile}
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl


# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
open:
  api:
    title: profile-service
    version: v1.0.0
    description: Profile Service
    serverUrl: http://${SWAGGER_HOST}:${server.port}
    serverName: server dev
    api-docs: profile-service